version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mydb
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306

  app:
    build: ./docker/tomcat
    container_name: myapp
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    environment:
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
    ports:
      - 80:8080
      - 8000:8000
    command: catalina.sh jpda run
    depends_on:
      - db

volumes:
  db-store:
